# Generated by Django 3.2.6 on 2021-08-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lens', models.CharField(choices=[('GR', 'Graph'), ('TR', 'Tree'), ('TX', 'Text'), ('LI', 'Link'), ('CH', 'Chronology'), ('AG', 'Aggregation')], default='GR', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.display')),
            ],
        ),
        migrations.CreateModel(
            name='DisplaySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('displays', models.ManyToManyField(through='Orgs.DisplayOrder', to='Orgs.Display')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('start_year_unknown', models.BooleanField(default=False, null=True)),
                ('start_month_unknown', models.BooleanField(default=False, null=True)),
                ('start_day_unknown', models.BooleanField(default=False, null=True)),
                ('end_date', models.DateField(null=True)),
                ('current', models.BooleanField(default=False, null=True)),
                ('end_year_unknown', models.BooleanField(default=False, null=True)),
                ('end_month_unknown', models.BooleanField(default=False, null=True)),
                ('end_day_unknown', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('start_year_unknown', models.BooleanField(default=False, null=True)),
                ('start_month_unknown', models.BooleanField(default=False, null=True)),
                ('start_day_unknown', models.BooleanField(default=False, null=True)),
                ('end_date', models.DateField(null=True)),
                ('current', models.BooleanField(default=False, null=True)),
                ('end_year_unknown', models.BooleanField(default=False, null=True)),
                ('end_month_unknown', models.BooleanField(default=False, null=True)),
                ('end_day_unknown', models.BooleanField(default=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('default_display_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orgs.displayset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sources_needed', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('input_format', models.CharField(choices=[('TEXT', 'TEXT'), ('INT', 'INT'), ('FLOAT', 'FLOAT'), ('DATE', 'DATE')], default='TEXT', max_length=5)),
                ('order', models.IntegerField()),
                ('tip_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Orgs.tipstructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sources_needed', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('input_format', models.CharField(choices=[('TEXT', 'TEXT'), ('INT', 'INT'), ('FLOAT', 'FLOAT'), ('DATE', 'DATE')], default='TEXT', max_length=5)),
                ('order', models.IntegerField()),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='Orgs.tip')),
                ('tip_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='Orgs.tipquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tip',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.tipstructure'),
        ),
        migrations.CreateModel(
            name='TieStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('left_tip_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_tie_structures', to='Orgs.tipstructure')),
                ('right_tip_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_tie_structures', to='Orgs.tipstructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TieQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sources_needed', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('input_format', models.CharField(choices=[('TEXT', 'TEXT'), ('INT', 'INT'), ('FLOAT', 'FLOAT'), ('DATE', 'DATE')], default='TEXT', max_length=5)),
                ('order', models.IntegerField()),
                ('tie_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Orgs.tiestructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TieFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sources_needed', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('input_format', models.CharField(choices=[('TEXT', 'TEXT'), ('INT', 'INT'), ('FLOAT', 'FLOAT'), ('DATE', 'DATE')], default='TEXT', max_length=5)),
                ('order', models.IntegerField()),
                ('tie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='Orgs.tie')),
                ('tie_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='Orgs.tiequestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tie',
            name='left_tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_ties', to='Orgs.tip'),
        ),
        migrations.AddField(
            model_name='tie',
            name='right_tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_ties', to='Orgs.tip'),
        ),
        migrations.AddField(
            model_name='tie',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.tiestructure'),
        ),
        migrations.AddField(
            model_name='displayset',
            name='tip_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_sets', to='Orgs.tipstructure'),
        ),
        migrations.AddField(
            model_name='displayorder',
            name='display_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.displayset'),
        ),
        migrations.AddField(
            model_name='display',
            name='left_tie_structures',
            field=models.ManyToManyField(related_name='displays_right', to='Orgs.TieStructure'),
        ),
        migrations.AddField(
            model_name='display',
            name='right_tie_structures',
            field=models.ManyToManyField(related_name='displays_left', to='Orgs.TieStructure'),
        ),
        migrations.AddField(
            model_name='display',
            name='second_level_display',
            field=models.ManyToManyField(to='Orgs.Display'),
        ),
        migrations.AddField(
            model_name='display',
            name='tip_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.tipstructure'),
        ),
        migrations.AlterUniqueTogether(
            name='displayorder',
            unique_together={('display', 'display_set')},
        ),
    ]
