# Generated by Django 3.2.5 on 2021-07-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lens', models.CharField(choices=[('GR', 'Graph'), ('TR', 'Tree'), ('TX', 'Text'), ('LI', 'Link'), ('CH', 'Chronology'), ('AG', 'Aggregation')], default='GR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.display')),
            ],
        ),
        migrations.CreateModel(
            name='DisplaySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('displays', models.ManyToManyField(through='Orgs.DisplayOrder', to='Orgs.Display')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('json_schema', models.JSONField(blank=True, null=True)),
                ('ui_schema', models.JSONField(blank=True, null=True)),
                ('jsonschema_library', models.CharField(choices=[('RJSF', 'React JSON Schema Form')], default='RJSF', max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('json_schema', models.JSONField(blank=True, null=True)),
                ('ui_schema', models.JSONField(blank=True, null=True)),
                ('jsonschema_library', models.CharField(choices=[('RJSF', 'React JSON Schema Form')], default='RJSF', max_length=4)),
                ('default_display_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orgs.displayset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValidEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_node_combos', to='Orgs.edgeschema')),
                ('left_node_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_valid_edges', to='Orgs.nodeschema')),
                ('right_node_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_valid_edges', to='Orgs.nodeschema')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('start_year_unknown', models.BooleanField(default=False, null=True)),
                ('start_month_unknown', models.BooleanField(default=False, null=True)),
                ('start_day_unknown', models.BooleanField(default=False, null=True)),
                ('end_date', models.DateField(null=True)),
                ('current', models.BooleanField(default=False, null=True)),
                ('end_year_unknown', models.BooleanField(default=False, null=True)),
                ('end_month_unknown', models.BooleanField(default=False, null=True)),
                ('end_day_unknown', models.BooleanField(default=False, null=True)),
                ('short_name', models.CharField(max_length=200)),
                ('aliases', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('json_data', models.JSONField(null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.nodeschema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('start_year_unknown', models.BooleanField(default=False, null=True)),
                ('start_month_unknown', models.BooleanField(default=False, null=True)),
                ('start_day_unknown', models.BooleanField(default=False, null=True)),
                ('end_date', models.DateField(null=True)),
                ('current', models.BooleanField(default=False, null=True)),
                ('end_year_unknown', models.BooleanField(default=False, null=True)),
                ('end_month_unknown', models.BooleanField(default=False, null=True)),
                ('end_day_unknown', models.BooleanField(default=False, null=True)),
                ('edge_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.edgeschema')),
                ('left_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_edges', to='Orgs.node')),
                ('right_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_edges', to='Orgs.node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='displayset',
            name='node_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_sets', to='Orgs.nodeschema'),
        ),
        migrations.AddField(
            model_name='displayorder',
            name='display_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.displayset'),
        ),
        migrations.AddField(
            model_name='display',
            name='parent_left_valid_edges',
            field=models.ManyToManyField(related_name='displays_right', to='Orgs.ValidEdge'),
        ),
        migrations.AddField(
            model_name='display',
            name='parent_node_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.nodeschema'),
        ),
        migrations.AddField(
            model_name='display',
            name='parent_right_valid_edges',
            field=models.ManyToManyField(related_name='displays_left', to='Orgs.ValidEdge'),
        ),
        migrations.AddField(
            model_name='display',
            name='second_level_display',
            field=models.ManyToManyField(to='Orgs.Display'),
        ),
        migrations.AlterUniqueTogether(
            name='displayorder',
            unique_together={('display', 'display_set')},
        ),
    ]
