# Generated by Django 3.1.7 on 2021-03-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first name', models.CharField(max_length=200)),
                ('second name', models.CharField(max_length=200)),
                ('middle name', models.CharField(max_length=200)),
                ('date of birth', models.DateField()),
            ],
        ),
    ]
