# Generated by Django 3.1.7 on 2021-03-29 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('start_year_unknown', models.BooleanField(default=False, null=True)),
                ('start_month_unknown', models.BooleanField(default=False, null=True)),
                ('start_day_unknown', models.BooleanField(default=False, null=True)),
                ('end_date', models.DateField(null=True)),
                ('current', models.BooleanField(default=False, null=True)),
                ('end_year_unknown', models.BooleanField(default=False, null=True)),
                ('end_month_unknown', models.BooleanField(default=False, null=True)),
                ('end_day_unknown', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EdgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('additional_schema', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('start_year_unknown', models.BooleanField(default=False, null=True)),
                ('start_month_unknown', models.BooleanField(default=False, null=True)),
                ('start_day_unknown', models.BooleanField(default=False, null=True)),
                ('end_date', models.DateField(null=True)),
                ('current', models.BooleanField(default=False, null=True)),
                ('end_year_unknown', models.BooleanField(default=False, null=True)),
                ('end_month_unknown', models.BooleanField(default=False, null=True)),
                ('end_day_unknown', models.BooleanField(default=False, null=True)),
                ('short_name', models.CharField(max_length=200)),
                ('aliases', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('json_data', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('additional_schema', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValidEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_node_combos', to='Orgs.edgetype')),
                ('left_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_edges_right_nodes', to='Orgs.nodetype')),
                ('right_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_edges_left_nodes', to='Orgs.nodetype')),
            ],
        ),
        migrations.DeleteModel(
            name='Org',
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.nodetype'),
        ),
        migrations.AddField(
            model_name='edge',
            name='edge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.edgetype'),
        ),
        migrations.AddField(
            model_name='edge',
            name='left_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_nodes', to='Orgs.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='right_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_nodes', to='Orgs.node'),
        ),
    ]
