# Generated by Django 3.1.7 on 2021-05-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_type', models.CharField(choices=[('GR', 'Graph'), ('TR', 'Tree'), ('TX', 'Text'), ('LI', 'Link'), ('CH', 'Chronology'), ('AG', 'Aggregation')], default='GR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.display')),
            ],
        ),
        migrations.CreateModel(
            name='DisplaySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displays', models.ManyToManyField(through='Orgs.DisplayOrder', to='Orgs.Display')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('start_year_unknown', models.BooleanField(default=False, null=True)),
                ('start_month_unknown', models.BooleanField(default=False, null=True)),
                ('start_day_unknown', models.BooleanField(default=False, null=True)),
                ('end_date', models.DateField(null=True)),
                ('current', models.BooleanField(default=False, null=True)),
                ('end_year_unknown', models.BooleanField(default=False, null=True)),
                ('end_month_unknown', models.BooleanField(default=False, null=True)),
                ('end_day_unknown', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EdgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('additional_schema', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('start_year_unknown', models.BooleanField(default=False, null=True)),
                ('start_month_unknown', models.BooleanField(default=False, null=True)),
                ('start_day_unknown', models.BooleanField(default=False, null=True)),
                ('end_date', models.DateField(null=True)),
                ('current', models.BooleanField(default=False, null=True)),
                ('end_year_unknown', models.BooleanField(default=False, null=True)),
                ('end_month_unknown', models.BooleanField(default=False, null=True)),
                ('end_day_unknown', models.BooleanField(default=False, null=True)),
                ('short_name', models.CharField(max_length=200)),
                ('aliases', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('json_data', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('additional_schema', models.JSONField(null=True)),
                ('default_display_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orgs.displayset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValidEdgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_node_combos', to='Orgs.edgetype')),
                ('left_node_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_edges_right_nodes', to='Orgs.nodetype')),
                ('right_node_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_edges_left_nodes', to='Orgs.nodetype')),
            ],
        ),
        migrations.DeleteModel(
            name='Org',
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.nodetype'),
        ),
        migrations.AddField(
            model_name='edge',
            name='edge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.edgetype'),
        ),
        migrations.AddField(
            model_name='edge',
            name='left_node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_edges', to='Orgs.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='right_node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_edges', to='Orgs.node'),
        ),
        migrations.AddField(
            model_name='displayset',
            name='node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_sets', to='Orgs.edgetype'),
        ),
        migrations.AddField(
            model_name='displayorder',
            name='display_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.displayset'),
        ),
        migrations.AddField(
            model_name='display',
            name='parent_node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.nodetype'),
        ),
        migrations.AddField(
            model_name='display',
            name='valid_edge_combinations',
            field=models.ManyToManyField(to='Orgs.ValidEdgeType'),
        ),
    ]
