# Generated by Django 3.2.5 on 2021-07-30 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='edgeschema',
            name='json_schema',
            field=models.JSONField(blank=True, help_text='Form JSON Schema.', null=True),
        ),
        migrations.AlterField(
            model_name='nodeschema',
            name='json_schema',
            field=models.JSONField(blank=True, help_text='Form JSON Schema.', null=True),
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('number', models.IntegerField()),
                ('name', models.TextField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='Orgs.buyer')),
                ('participants', models.ManyToManyField(null=True, related_name='tenders', to='Orgs.Seller')),
                ('red_flags', models.ManyToManyField(null=True, related_name='tenders', to='Orgs.RedFlag')),
            ],
        ),
    ]
