# Generated by Django 3.1.7 on 2021-04-02 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0002_auto_20210329_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='left_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_edges', to='Orgs.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='right_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_edges', to='Orgs.node'),
        ),
    ]
