# Generated by Django 3.2.5 on 2021-07-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0002_auto_20210730_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='red_flags',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='RedFlag',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Tender',
        ),
    ]
