# Generated by Django 3.1.7 on 2021-05-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0003_auto_20210513_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayset',
            name='name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
