# Generated by Django 3.1.7 on 2021-03-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0003_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start date', models.DateField()),
                ('end date', models.DateField()),
                ('additional info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PositionName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.positionname'),
        ),
    ]
