# Generated by Django 3.1.7 on 2021-05-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0005_auto_20210513_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgetype',
            name='jsonschema_library',
            field=models.CharField(choices=[('RJSF', 'React JSON Schema Form')], default='RJSF', max_length=4),
        ),
        migrations.AddField(
            model_name='edgetype',
            name='ui_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='jsonschema_library',
            field=models.CharField(choices=[('RJSF', 'React JSON Schema Form')], default='RJSF', max_length=4),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='ui_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edgetype',
            name='json_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='json_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
