# Generated by Django 3.1.7 on 2021-03-12 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0005_auto_20210312_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orgs.org'),
        ),
        migrations.AddField(
            model_name='employment',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orgs.person'),
        ),
        migrations.AddField(
            model_name='employment',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orgs.position'),
        ),
    ]
