# Generated by Django 3.1.7 on 2021-05-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0006_auto_20210513_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='left_node_type',
            new_name='left_node',
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='right_node_type',
            new_name='right_node',
        ),
    ]
