# Generated by Django 3.1.7 on 2021-03-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0006_auto_20210312_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='middle name',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='second name',
            new_name='second_name',
        ),
    ]
