# Generated by Django 3.1.7 on 2021-05-25 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0007_auto_20210525_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validedgetype',
            name='left_node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_valid_edge_types', to='Orgs.nodetype'),
        ),
        migrations.AlterField(
            model_name='validedgetype',
            name='right_node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_valid_edge_types', to='Orgs.nodetype'),
        ),
    ]
