# Generated by Django 3.1.7 on 2021-03-12 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0007_auto_20210312_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='end date',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='start date',
        ),
        migrations.AddField(
            model_name='employment',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1900), django.core.validators.MinValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='employment',
            name='additional info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
