# Generated by Django 3.1.7 on 2021-07-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0008_auto_20210525_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display',
            old_name='valid_edge_combinations',
            new_name='parent_left_valid_edges',
        ),
    ]
