# Generated by Django 3.1.7 on 2021-03-12 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0008_auto_20210312_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='org',
        ),
        migrations.AlterField(
            model_name='employment',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1950)]),
        ),
    ]
