# Generated by Django 3.1.7 on 2021-07-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0009_auto_20210719_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='parent_right_valid_edges',
            field=models.ManyToManyField(related_name='displays_right', to='Orgs.ValidEdgeType'),
        ),
        migrations.AlterField(
            model_name='display',
            name='parent_left_valid_edges',
            field=models.ManyToManyField(related_name='displays_left', to='Orgs.ValidEdgeType'),
        ),
    ]
