# Generated by Django 3.1.7 on 2021-03-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0010_auto_20210312_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='additional info',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='start_day',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='start_year',
        ),
    ]
