# Generated by Django 3.1.7 on 2021-07-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0010_auto_20210719_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='second_level_display',
            field=models.ManyToManyField(to='Orgs.Display'),
        ),
        migrations.AlterUniqueTogether(
            name='displayorder',
            unique_together={('display', 'display_set')},
        ),
    ]
