# Generated by Django 3.1.7 on 2021-03-12 11:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0011_auto_20210312_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='additional info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='end_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='employment',
            name='end_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='employment',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1950)]),
        ),
        migrations.AddField(
            model_name='employment',
            name='start_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='employment',
            name='start_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='employment',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1950)]),
        ),
        migrations.AlterField(
            model_name='employment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.person'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.position'),
        ),
    ]
