# Generated by Django 3.1.7 on 2021-03-12 11:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0012_auto_20210312_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='additional info',
            new_name='additional_info',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date of birth',
        ),
        migrations.AddField(
            model_name='person',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1800)]),
        ),
        migrations.AddField(
            model_name='position',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='end_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='position',
            name='end_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='position',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1950)]),
        ),
        migrations.AddField(
            model_name='position',
            name='start_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='position',
            name='start_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='position',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1950)]),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.positionname'),
        ),
        migrations.AlterField(
            model_name='position',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.org'),
        ),
    ]
