# Generated by Django 3.1.7 on 2021-03-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0017_orgpositionhierarchyrel_positionshierarchyrel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='predecessor_orgs',
            field=models.ManyToManyField(blank=True, null=True, related_name='_org_predecessor_orgs_+', to='Orgs.Org'),
        ),
        migrations.AlterField(
            model_name='orgsstructuralrel',
            name='external_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_org_data', to='Orgs.org'),
        ),
        migrations.AlterField(
            model_name='orgsstructuralrel',
            name='internal_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_org_data', to='Orgs.org'),
        ),
    ]
