# Generated by Django 3.1.7 on 2021-03-18 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0018_auto_20210315_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgshierarchyrel',
            name='subordinate_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superior_orgs', to='Orgs.org'),
        ),
        migrations.AlterField(
            model_name='orgshierarchyrel',
            name='superior_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinate_orgs', to='Orgs.org'),
        ),
        migrations.AlterField(
            model_name='orgsstructuralrel',
            name='external_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_orgs', to='Orgs.org'),
        ),
        migrations.AlterField(
            model_name='orgsstructuralrel',
            name='internal_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_orgs', to='Orgs.org'),
        ),
        migrations.RemoveField(
            model_name='position',
            name='org',
        ),
        migrations.AddField(
            model_name='position',
            name='org',
            field=models.ManyToManyField(related_name='positions', to='Orgs.Org'),
        ),
    ]
