# Generated by Django 3.1.7 on 2021-03-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0019_auto_20210318_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='org',
            new_name='orgs',
        ),
    ]
