# Generated by Django 3.1.7 on 2021-03-25 13:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0020_auto_20210318_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1950)])),
                ('start_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('start_day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('end_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1950)])),
                ('end_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('end_day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EdgeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1950)])),
                ('start_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('start_day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('end_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1950)])),
                ('end_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('end_day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='orgpositionhierarchyrel',
            name='subordinate_position',
        ),
        migrations.RemoveField(
            model_name='orgpositionhierarchyrel',
            name='superior_org',
        ),
        migrations.RemoveField(
            model_name='orgshierarchyrel',
            name='subordinate_org',
        ),
        migrations.RemoveField(
            model_name='orgshierarchyrel',
            name='superior_org',
        ),
        migrations.RemoveField(
            model_name='orgsstructuralrel',
            name='external_org',
        ),
        migrations.RemoveField(
            model_name='orgsstructuralrel',
            name='internal_org',
        ),
        migrations.RemoveField(
            model_name='positionorghierarchyrel',
            name='subordinate_org',
        ),
        migrations.RemoveField(
            model_name='positionorghierarchyrel',
            name='superior_position',
        ),
        migrations.RemoveField(
            model_name='positionshierarchyrel',
            name='subordinate_position',
        ),
        migrations.RemoveField(
            model_name='positionshierarchyrel',
            name='superior_position',
        ),
        migrations.RemoveField(
            model_name='org',
            name='description',
        ),
        migrations.RemoveField(
            model_name='org',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='org',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='org',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='org',
            name='id',
        ),
        migrations.RemoveField(
            model_name='org',
            name='predecessor_orgs',
        ),
        migrations.RemoveField(
            model_name='org',
            name='start_day',
        ),
        migrations.RemoveField(
            model_name='org',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='org',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='person',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.RemoveField(
            model_name='position',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='position',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='position',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='position',
            name='id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='orgs',
        ),
        migrations.RemoveField(
            model_name='position',
            name='start_day',
        ),
        migrations.RemoveField(
            model_name='position',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='position',
            name='start_year',
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.DeleteModel(
            name='OrgPositionHierarchyRel',
        ),
        migrations.DeleteModel(
            name='OrgsHierarchyRel',
        ),
        migrations.DeleteModel(
            name='OrgsStructuralRel',
        ),
        migrations.DeleteModel(
            name='PositionOrgHierarchyRel',
        ),
        migrations.DeleteModel(
            name='PositionsHierarchyRel',
        ),
        migrations.AddField(
            model_name='edge',
            name='left_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_nodes', to='Orgs.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgs.edgename'),
        ),
        migrations.AddField(
            model_name='edge',
            name='right_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_nodes', to='Orgs.node'),
        ),
        migrations.AddField(
            model_name='org',
            name='node_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Orgs.node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='node_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Orgs.node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='node_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Orgs.node'),
            preserve_default=False,
        ),
    ]
