# Generated by Django 3.1.7 on 2021-03-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgs', '0021_auto_20210325_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EdgeName',
            new_name='EdgeType',
        ),
        migrations.RenameModel(
            old_name='PositionName',
            new_name='PositionType',
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='name',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='edgetype',
            old_name='name',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='org',
            old_name='name',
            new_name='aliases',
        ),
        migrations.RenameField(
            model_name='positiontype',
            old_name='name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name',
        ),
        migrations.AddField(
            model_name='node',
            name='short_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='type',
            field=models.ManyToManyField(to='Orgs.PositionType'),
        ),
    ]
